apiVersion: v1
kind: Service
metadata:
  name: db-svc-127878254
  namespace: clinic-127878254
spec:
  type: ClusterIP
  selector:
    app: db
    owner: "127878254"
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
