apiVersion: v1
kind: ConfigMap
metadata:
  name: db-seed-127878254
  namespace: clinic-127878254
data:
  01-seed.sql: |
    CREATE DATABASE IF NOT EXISTS clinicdb;
    USE clinicdb;
    CREATE TABLE IF NOT EXISTS clinic_items (
      id INT PRIMARY KEY AUTO_INCREMENT,
      item_name VARCHAR(100) NOT NULL,
      student_id VARCHAR(30) NOT NULL
    );
    INSERT INTO clinic_items (item_name, student_id) VALUES
      ('dns-check-1', '127878254'),
      ('dns-check-2', '127878254'),
      ('service-check-3', '127878254'),
      ('endpoint-check-4', '127878254'),
      ('coredns-check-5', '127878254');
