apiVersion: v1
kind: Service
metadata:
  name: web-svc-127878254
  namespace: clinic-127878254
spec:
  type: NodePort
  selector:
    app: web
    owner: "127878254"
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
